---
deployment:
  tasks:
    - /opt/alt/alt-nodejs16/root/bin/npm install
    - /opt/alt/alt-nodejs16/root/bin/npm run build
    - export DEPLOYPATH=/home/dqwbuokw/public_html/react-sample
    - /bin/cp -R build/* $DEPLOYPATH
