---
deployment:
  tasks:
    - /opt/alt/alt-nodejs16/root/bin/npm install --prefix /home/dqwbuokw/repositories/react-sample
    - /opt/alt/alt-nodejs16/root/bin/npm run build --prefix /home/dqwbuokw/repositories/react-sample
    - export DEPLOYPATH=/home/dqwbuokw/public_html/react-sample
    - /bin/cp -R build/* $DEPLOYPATH
